# Generated by Django 2.1.9 on 2020-05-04 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('News_ID', models.CharField(max_length=100)),
                ('News_Title', models.CharField(max_length=100)),
                ('News_Body', models.CharField(max_length=2000)),
                ('News_Image', models.ImageField(upload_to='newsimages/')),
            ],
            options={
                'db_table': 'NewsData',
            },
        ),
    ]
