# Generated by Django 2.1.9 on 2020-05-04 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_News_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Video_News_ID', models.CharField(max_length=100)),
                ('Video_News_Title', models.CharField(max_length=100)),
                ('Video_News_Body', models.CharField(max_length=2000)),
                ('Video_News_Image', models.ImageField(upload_to='newsvideos/')),
            ],
            options={
                'db_table': 'VideoNewsData',
            },
        ),
    ]
