# Generated by Django 2.1.9 on 2020-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videonewsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videonewsdata',
            name='Video_News_Image',
            field=models.FileField(upload_to='newsvideos/'),
        ),
    ]
