# Generated by Django 2.1.9 on 2020-05-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200505_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videonewsdata',
            old_name='Video_News_Image',
            new_name='News_Video',
        ),
    ]
