# Generated by Django 2.1.9 on 2020-05-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='User_Password',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
