# Generated by Django 2.1.9 on 2020-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userdata_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=100)),
                ('User_Image', models.FileField(upload_to='userprofilepictures/')),
            ],
            options={
                'db_table': 'UserProfilePicture',
            },
        ),
    ]
