# Generated by Django 2.1.9 on 2020-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_ID', models.CharField(max_length=100)),
                ('Category_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BookCategoryData',
            },
        ),
    ]
