# Generated by Django 2.1.9 on 2020-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bookcategorydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_ID', models.CharField(max_length=100)),
                ('Book_Name', models.CharField(max_length=100)),
                ('Book_Category', models.CharField(max_length=100)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Book_About', models.CharField(max_length=1000)),
                ('Book_Cover', models.ImageField(upload_to='bookcover/')),
                ('Book_PDF', models.FileField(upload_to='bookpdf/')),
                ('Download', models.CharField(default='0', max_length=100)),
            ],
            options={
                'db_table': 'BookData',
            },
        ),
    ]
