# Generated by Django 2.1.9 on 2020-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bookdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=100)),
                ('Book_ID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserBooks',
            },
        ),
    ]
