# Generated by Django 2.1.9 on 2020-05-08 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCommentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_ID', models.CharField(max_length=100)),
                ('Comment_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('News_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'NewsCommentData',
            },
        ),
    ]
