# Generated by Django 2.1.9 on 2020-05-09 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_newscommentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_ID', models.CharField(max_length=100)),
                ('Campaign_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Campaign_Title', models.CharField(max_length=1000)),
                ('Campaign_About', models.CharField(max_length=2000)),
                ('Campaign_Donation', models.CharField(max_length=50)),
                ('Campaign_Images', models.FileField(upload_to='campaignimages/')),
            ],
            options={
                'db_table': 'CampaignData',
            },
        ),
    ]
