# Generated by Django 2.1.9 on 2020-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_campaigndata'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='User_ID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='Campaign_About',
            field=models.CharField(default='NA', max_length=2000),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='Campaign_Donation',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='Campaign_Title',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
