# Generated by Django 2.1.9 on 2020-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200509_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='Campaign_Account_Bank',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='Campaign_Account_IFSC',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='Campaign_Account_Name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='Campaign_Account_Number',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
