# Generated by Django 2.1.9 on 2020-05-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200510_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='Campaign_Status',
            field=models.CharField(default='Deactive', max_length=50),
        ),
    ]
