# Generated by Django 2.1.9 on 2020-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_donationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitorCount', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'VisitorsData',
            },
        ),
    ]
