# Generated by Django 2.1.9 on 2020-05-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_visitorsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorsData',
        ),
    ]
